### ISSUE TITLE
Move products to root url

### ISSUE THREAD

**Issue by johnpooch** [mlenahan/e-commerce#19]
Right now we have to navigate to `/products` to get to the home page.

Ideally we'd like to arrive at the home page by just doing http://localhost:8069/

I think this is a fairly easy fix. Just gotta edit `project.urls` I think.

**Comment by mlenahan** [comment]
I just changed it from `path('products/', include('products.urls')),` to `path('', include('products.urls')),` and that seems to work as intended?

**Comment by johnpooch** [comment]
Yep :) PR it up
